### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by khusnan21** [atulkadian/gdrivemirror_bot#4]
After install requirements i try run bot.py i got this error
$ python bot.py                                           
$ File "bot.py", line 140
    os.remove(raw_file)                                                       ^                                 TabError: inconsistent use of tabs and spaces in indentation

**Comment by indraskr9** [comment]
use required python version, see readme :/

**Comment by DNI9** [comment]
use required python version, see readme :/

**Comment by khusnan21** [comment]
Ok done thanks
